# Generated by Django 5.2.5 on 2025-09-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create Ticket'), ('ASSIGN', 'Assign/Reassign'), ('STATUS', 'Change Status'), ('COMMENT', 'Comment'), ('ATTACH', 'Attachment'), ('SLA_WARN', 'SLA Warning'), ('SLA_BREACH', 'SLA Breach')], max_length=20),
        ),
    ]
