# Generated by Django 5.2.6 on 2025-09-04 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("max_hours", models.PositiveIntegerField(default=4)),
                ("min_notice_hours", models.PositiveIntegerField(default=1)),
                ("allow_weekends", models.BooleanField(default=True)),
                ("buffer_minutes", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "booking_policy",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("room", "Sala"),
                            ("device", "Equipo"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "booking_resource",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitada"),
                            ("approved", "Aprobada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="tickets.resource",
                    ),
                ),
            ],
            options={
                "db_table": "booking_reservation",
                "ordering": ["-starts_at"],
            },
        ),
    ]
