# Generated by Django 5.2.6 on 2025-09-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_eventlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Policy",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
    ]
