# Generated by Django 5.2.6 on 2025-09-22 19:46

from django.db import migrations


def assign_sequential_codes(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    for ticket in Ticket.objects.all().order_by("id"):
        desired = str(ticket.pk)
        if ticket.code != desired:
            Ticket.objects.filter(pk=ticket.pk).update(code=desired)


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0010_delete_policy_remove_reservation_resource_and_more"),
    ]

    operations = [
        migrations.RunPython(assign_sequential_codes, migrations.RunPython.noop),
    ]
