# Generated by Django 5.2.6 on 2025-09-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0011_assign_sequential_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="kind",
            field=models.CharField(
                choices=[("INCIDENT", "Incidente"), ("REQUEST", "Solicitud")],
                default="REQUEST",
                help_text="Clasificación funcional del ticket (incidente o solicitud)",
                max_length=20,
            ),
        ),
    ]
