# Generated by Django 5.2.6 on 2025-09-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="priority",
            old_name="key",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="priority",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
