from accounts.roles import ROLE_ADMIN, ROLE_TECH


PERMISSION_LABELS = {
    "add_ticket": "Puede agregar ticket",
    "change_ticket": "Puede cambiar ticket",
    "delete_ticket": "Puede eliminar ticket",
    "view_ticket": "Puede ver ticket",
    "assign_ticket": "Puede asignar ticket",
    "transition_ticket": "Puede cambiar estado de ticket",
    "comment_internal": "Puede comentar internamente",
    "view_all_tickets": "Puede ver todos los tickets",
    "add_ticketcomment": "Puede agregar comentario",
    "change_ticketcomment": "Puede cambiar comentario",
    "delete_ticketcomment": "Puede eliminar comentario",
    "view_ticketcomment": "Puede ver comentario",
    "add_ticketattachment": "Puede agregar adjunto",
    "change_ticketattachment": "Puede cambiar adjunto",
    "delete_ticketattachment": "Puede eliminar adjunto",
    "view_ticketattachment": "Puede ver adjunto",
    "add_category": "Puede agregar categoría",
    "change_category": "Puede cambiar categoría",
    "delete_category": "Puede eliminar categoría",
    "view_category": "Puede ver categoría",
    "add_priority": "Puede agregar prioridad",
    "change_priority": "Puede cambiar prioridad",
    "delete_priority": "Puede eliminar prioridad",
    "view_priority": "Puede ver prioridad",
    "add_area": "Puede agregar área",
    "change_area": "Puede cambiar área",
    "delete_area": "Puede eliminar área",
    "view_area": "Puede ver área",
    # Permisos de usuarios y roles (auth)
    "add_user": "Puede agregar usuario",
    "change_user": "Puede cambiar usuario",
    "delete_user": "Puede eliminar usuario",
    "view_user": "Puede ver usuario",
    "add_group": "Puede agregar rol",
    "change_group": "Puede cambiar rol",
    "delete_group": "Puede eliminar rol",
    "view_group": "Puede ver rol",
    "add_permission": "Puede agregar permiso",
    "change_permission": "Puede cambiar permiso",
    "delete_permission": "Puede eliminar permiso",
    "view_permission": "Puede ver permiso",
    # Permisos del sistema y administración
    "add_logentry": "Puede agregar registro de admin",
    "change_logentry": "Puede cambiar registro de admin",
    "delete_logentry": "Puede eliminar registro de admin",
    "view_logentry": "Puede ver registro de admin",
    "add_contenttype": "Puede agregar tipo de contenido",
    "change_contenttype": "Puede cambiar tipo de contenido",
    "delete_contenttype": "Puede eliminar tipo de contenido",
    "view_contenttype": "Puede ver tipo de contenido",
    "add_session": "Puede agregar sesión",
    "change_session": "Puede cambiar sesión",
    "delete_session": "Puede eliminar sesión",
    "view_session": "Puede ver sesión",
}


PERMISSION_TEMPLATES = {
    ROLE_ADMIN: {
        "label": "Administrador",
        "description": "Acceso completo a la configuración, catálogos y tickets.",
        "codenames": list(PERMISSION_LABELS.keys()),
    },
    ROLE_TECH: {
        "label": "Técnico",
        "description": "Enfoque operativo: trabajar tickets, comentar y gestionar adjuntos.",
        "codenames": [
            "view_ticket",
            "change_ticket",
            "transition_ticket",
            "view_all_tickets",
            "comment_internal",
            "add_ticketcomment",
            "change_ticketcomment",
            "view_ticketcomment",
            "add_ticketattachment",
            "view_ticketattachment",
        ],
    },
}
